### PR TITLE
Format JS with Prettier

### PR DESCRIPTION
**Pull request by irskep**
Having a .prettierrc means anybody who uses format-on-save will automatically follow project conventions. I used 2-space tabs because that's what you put in .editorconfig, and otherwise just left all the default settings alone.

A step further would be to add a CI job which fails if the submitter _doesn’t_ use the formatter, but I'll let you decide if you want to go that far. I'd be happy to write the config file to make that happen.

I included a vscode config to make it more likely that future contributors do the right thing. I didn't realize until #17 that it also formats CSS, so hopefully that's OK. I can scope it down to just JS if necessary.

### CODE REVIEW

**Comment by irskep** [comment]
Tacked on a commit (with a good message) doing the camelCase conversion, and converting 'var' to 'let', since 'var' is essentially deprecated now. Figured it would be better to do all the trivial formatting changes in one go.

**Comment by cu** [comment]
Thanks for doing this.

The more that I look at it, the more I'm unsure about switching all the JS to 2-space indentation. I know that's the de facto standard pretty much everywhere now. And maybe it looks fine for someone who has been steeped in Javascript for a good long while, but I tried to give it a chance by reading the modified sections in github and also in vscode, but it's just not working for me. I find it harder to read and sadly I can use all the help I can get!

I'm guessing the last section in `.editorconfig` including `*.js` was either an oversight or overenthusiastic aspiration. That said, I'm fine with adding `.prettierrc` and the vscode config, and letting fix up the other formatting issues.

So, I think I can accept this, with the following changes:

1. Adjust `.editorconfig` js indent to 4. (Just remove it from the glob I think?)
2. `.prettierrc` `tabWidth` to 4
3. Drop the indentation-only changes but let Prettier have its way with the rest of the formatting.

**Comment by cu** [comment]
I am okay with the second commit but I think it should be its own PR.

**Comment by irskep** [comment]
Oh I'm completely fine with 4-space tabs, I was just going by what was there already. I don't think there's a firm standard one way or the other. Will make the changes.

**Comment by irskep** [comment]
Updated!

**Pull request merged**
